# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/lquinones/Documents/LeoLab/UE/UEEditor/Linux_Unreal_Engine_5.6.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	ownueui-Android-DebugGame  \
	ownueui-Android-Development  \
	ownueui-Android-Shipping  \
	ownueui-Linux-DebugGame  \
	ownueui-Linux-Development  \
	ownueui-Linux-Shipping  \
	ownueui-LinuxArm64-DebugGame  \
	ownueui-LinuxArm64-Development  \
	ownueui-LinuxArm64-Shipping  \
	ownueui \
	ownueuiEditor-Linux-DebugGame  \
	ownueuiEditor-Linux-Development  \
	ownueuiEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend ownueuiEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug ownueuiEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

ownueui-Android-DebugGame:
	 $(BUILD) ownueui Android DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-Android-Development:
	 $(BUILD) ownueui Android Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-Android-Shipping:
	 $(BUILD) ownueui Android Shipping  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-Linux-DebugGame:
	 $(BUILD) ownueui Linux DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-Linux-Development:
	 $(BUILD) ownueui Linux Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-Linux-Shipping:
	 $(BUILD) ownueui Linux Shipping  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-LinuxArm64-DebugGame:
	 $(BUILD) ownueui LinuxArm64 DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-LinuxArm64-Development:
	 $(BUILD) ownueui LinuxArm64 Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui-LinuxArm64-Shipping:
	 $(BUILD) ownueui LinuxArm64 Shipping  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueui: ownueui-Linux-Development

ownueuiEditor-Linux-DebugGame:
	 $(BUILD) ownueuiEditor Linux DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueuiEditor-Linux-Development:
	 $(BUILD) ownueuiEditor Linux Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" $(ARGS)

ownueuiEditor: ownueuiEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/lquinones/Documents/LeoLab/UEProjects/unreallab-ui/ownueui.uproject" -Game 

.PHONY: $(TARGETS)
